server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: booking
    password: booking
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

app:
  jwt:
    secret: "CHANGE_ME_IN_PROD_CHANGE_ME_IN_PROD_CHANGE_ME_IN_PROD_123456"
    expirationMinutes: 120
  files:
    storageDir: ./storage

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
